language: objective-c
xcode_project: Example/UIImageViewModeScaleAspect/UIImageViewModeScaleAspect.xcodeproj 
xcode_scheme: UIImageViewModeScaleAspectTests
script: 
        - xctool test -project ./Example/UIImageViewModeScaleAspect/UIImageViewModeScaleAspect.xcodeproj -scheme UIImageViewModeScaleAspectTests -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
        - bash <(curl -s https://codecov.io/bash)
